CREATE TABLE USUARIO (
  ID_USUARIO INT(11) PRIMARY KEY AUTO_INCREMENT,
  CORREO VARCHAR(255),
  PASS VARCHAR(255),
  TIPO VARCHAR(255)
);

CREATE TABLE DOMICILIO (
  ID_DOMICILIO INT(11) PRIMARY KEY AUTO_INCREMENT,
  CALLE VARCHAR(255),
  CIUDAD VARCHAR(255),
  ESTADO VARCHAR(255),
  CODIGO_POSTAL VARCHAR(255),
  ID_USUARIO INT(11),
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE REDESSOCIALES (
  ID_RED INT PRIMARY KEY AUTO_INCREMENT,
  RED_NOMBRE VARCHAR(255),
  RED_URI VARCHAR(255),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE CANDIDATO (
  ID_CANDIDATO INT PRIMARY KEY AUTO_INCREMENT,
  CAN_NOMBRE VARCHAR(255),
  CAN_APELLIDO VARCHAR(255),
  CAN_TELEFONO VARCHAR(255),
  CAN_GENERO VARCHAR(255),
  CAN_FECHANACIMIENTO DATE,
  AREA VARCHAR(255),
  PUESTO VARCHAR(255),
  CAN_FOTOPERFIL VARCHAR(255),
  CAN_FOTOPORTADA VARCHAR(255),
  CAN_CURRICULUM VARCHAR(255),
  CAN_ACERCA TEXT,
  CAN_PORTAFOLIO VARCHAR(255),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

#altera la tabla canidato añadiendo can_portafolio varchar(255) y can_curriculum varchar(255)
ALTER TABLE CANDIDATO ADD CAN_PORTAFOLIO VARCHAR(255);

CREATE TABLE IDIOMA (
  ID_IDIOMA INT PRIMARY KEY AUTO_INCREMENT,
  IDIOMA_NOMBRE VARCHAR(255),
  IDIOMA_NIVEL VARCHAR(255),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE INSIGNIAS (
  ID_INSIGNIA INT PRIMARY KEY AUTO_INCREMENT,
  INS_NOMBRE VARCHAR(255),
  INS_NIVEL INT(11),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE HABILIDAD (
  ID_HABILIDAD INT PRIMARY KEY AUTO_INCREMENT,
  HAB_NOMBRE VARCHAR(255),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE EDUCACION (
  ID_EDUCACION INT PRIMARY KEY AUTO_INCREMENT,
  EDU_NOMBRE_INSTITUCION VARCHAR(255),
  EDU_FECHA_INICIO DATE,
  EDU_FECHA_FIN DATE,
  EDU_TITULO VARCHAR(255),
  EDU_NIVEL VARCHAR(255),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE EXPERIENCIA (
  ID_EXPERIENCIA INT PRIMARY KEY AUTO_INCREMENT,
  EXP_NOMBRE_EMPRESA VARCHAR(255),
  EXP_DESCRIPCION TEXT,
  EXP_CARGO VARCHAR(255),
  EXP_DURACION VARCHAR(255),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE PROYECTOS (
  ID_PROYECTO INT PRIMARY KEY AUTO_INCREMENT,
  PROY_NOMBRE VARCHAR(255),
  PROY_DESCRIPCION TEXT,
  PROY_TECNOLOGIA VARCHAR(255),
  PROY_URL VARCHAR(255),
  PROY_FOTO VARCHAR(255),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE CERTIFICACIONES (
  ID_CERTIFICACION INT PRIMARY KEY AUTO_INCREMENT,
  CER_NOMBRE VARCHAR(255),
  CER_DESCRIPCION TEXT,
  CER_LUGAR VARCHAR(255),
  CER_FECHA DATE,
  CER_HORAS INT(10),
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE EMPRESA (
  ID_EMPRESA INT(11) PRIMARY KEY AUTO_INCREMENT,
  EMP_NOMBRE VARCHAR(255),
  EMP_APELLIDO VARCHAR(255),
  EMP_TELEFONO VARCHAR(255),
  EMP_EMPRESA VARCHAR(255),
  EMP_FOTOPERFIL VARCHAR(255),
  EMP_FOTOPORTADA VARCHAR(255),
  EMP_GENERO VARCHAR(255),
  EMP_ACERCA TEXT,
  EMP_NACIMIENTO DATE,
  EMP_CARGO VARCHAR(255),
  EMP_URL VARCHAR(255),
  EMP_FOTORECLUTADOR VARCHAR(255),
  ID_USUARIO INT(11),
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE VACANTE (
  ID_VACANTE INT(11) PRIMARY KEY AUTO_INCREMENT,
  TITULO VARCHAR(255),
  DESCRIPCION TEXT,
  SALARIO DECIMAL(10, 2),
  CIUDAD VARCHAR(255),
  ESTADO VARCHAR(255),
  AREA VARCHAR(255),
  PUESTO VARCHAR(255),
  EDUCACION VARCHAR(255),
  TIPO_CONTRATO VARCHAR(255),
  HORARIO VARCHAR(255),
  MODO_TRABAJO VARCHAR(255),
  VENCIMIENTO DATE,
  NUMERO_VACANTES INT(11),
  ID_EMPRESA INT(11),
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA)
);

CREATE TABLE EMPRESA_VACANTE (
  ID_EMPRESA INT(11),
  ID_VACANTE INT(11),
  FECHA_CREACION_VACANTE DATE,
  PRIMARY KEY (ID_EMPRESA, ID_VACANTE),
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  FOREIGN KEY (ID_VACANTE) REFERENCES VACANTE (ID_VACANTE)
);

CREATE TABLE POSTULACION (
  ID_POSTULACION INT(11) PRIMARY KEY AUTO_INCREMENT,
  ID_CANDIDATO INT(11),
  ID_VACANTE INT(11),
  FECHA_POSTULACION DATE,
  ESTADO VARCHAR(255),
  FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO (ID_CANDIDATO),
  FOREIGN KEY (ID_VACANTE) REFERENCES VACANTE (ID_VACANTE)
);

CREATE TABLE SUBSCRIPCION (
  ID_SUBSCRIPCION INT PRIMARY KEY AUTO_INCREMENT,
  ID_EMPRESA INT(11),
  FECHA_INICIO DATE,
  FECHA_VENCIMIENTO DATE,
  TIPO_SUSCRIPCION VARCHAR(255),
  ESTADO_SUSCRIPCION VARCHAR(255),
  COSTO DECIMAL(10, 2),
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA)
);

CREATE TABLE CITA (
  ID_CITA INT PRIMARY KEY AUTO_INCREMENT,
  ID_CANDIDATO INT(11),
  ID_EMPRESA INT(11),
  FECHA_CITA DATE,
  HORA_CITA TIME,
  FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO (ID_CANDIDATO),
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA)
)

CREATE TABLE DOCUMENTOS(
  ID_DOCUMENTO INT PRIMARY KEY AUTO_INCREMENT,
  ID_USUARIO INT(11),
  NOMBRE_DOCUMENTO VARCHAR(255),
  RUTA_DOCUMENTO VARCHAR(255),
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
)

CREATE TABLE PAGO (
  ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
  ID_SUBSCRIPCION INT(11),
  FECHA_PAGO DATE,
  COSTO DECIMAL(10, 2),
  FOREIGN KEY (ID_SUBSCRIPCION) REFERENCES SUBSCRIPCION (ID_SUBSCRIPCION)
);

CREATE TABLE MENSAJE (
  ID_MENSAJE INT PRIMARY KEY AUTO_INCREMENT,
  ID_USUARIO_EMISOR INT(11),
  ID_USUARIO_RECEPTOR INT(11),
  MENSAJE TEXT,
  FECHA_MENSAJE DATE,
  FOREIGN KEY (ID_USUARIO_EMISOR) REFERENCES USUARIO (ID_USUARIO),
  FOREIGN KEY (ID_USUARIO_RECEPTOR) REFERENCES USUARIO (ID_USUARIO)
);

